services:
  mail2webhook-build:
    build:
      context: .
      dockerfile: Dockerfile
    image: mail2webhook:local
    container_name: mail2webhook-build
    ports:
      - "8888:8080"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
